name: Test pull requests and generate preview link

on:
  pull_request:
    branches: [main]

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: npm
      - name: Test build
        run: |
          npm install --frozen-lockfile
          npm run build
      - name: Installing Surge
        run: npm i -g surge
      - name: Deploying on Surge
        env:
          SURGE_LOGIN: sustainableedufoundation@gmail.com
          SURGE_TOKEN: 4f75270ec1d0e4d48c5ecc3959f9d888
          DEPLOY_DOMAIN: https://pr-${{ github.event.number }}-sef-handbook.surge.sh
        run: surge ./ $DEPLOY_DOMAIN --token $SURGE_TOKEN
